"""
Accentuation Peer-Review Figure Export
=======================================
See acc_peer_review_analysis.md for full documentation.

Two sessions combined:
  - Accentuation session (red_20250504-20250512): neural responses to NSD + accentuated images
  - Encoding session    (red_20250428-20250430):  model predicted responses for all stimuli

Key experiment: 2x2 (accentuator x reviewer) scatter of neural vs predicted response on
accentuated images — tests whether neural responses track reviewer predictions on stimuli
generated by the accentuator model.
"""

import os
import sys
import pickle as pkl
from os.path import join

import numpy as np
import pandas as pd
import matplotlib
matplotlib.rcParams["pdf.fonttype"] = 42
matplotlib.rcParams["ps.fonttype"]  = 42
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import pearsonr
from sklearn.metrics import r2_score

sys.path.append("/n/home12/binxuwang/Github/Closed-loop-visual-insilico")
from core.data_utils import load_from_hdf5
from core.posthoc_prediction_utils import parse_accentuated_filenames_to_df
from circuit_toolkit.plot_utils import saveallforms

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
ACC_SESSION_ID      = "red_20250504-20250512"    # neural data session
ENCODING_SESSION_ID = "red_20250428-20250430"    # model prediction session

EPHYS_DIR    = "/n/holylabs/LABS/alvarez_lab/Lab/VVS_Accentuation/Ephys_Data"
ENCODING_DIR = "/n/holylabs/LABS/alvarez_lab/Lab/VVS_Accentuation/Encoding_models"
FIGDIR       = "/n/home12/binxuwang/Github/Closed-loop-visual-insilico/figures/peer_review_export"

ACCENTUATOR_LIST = ["resnet50_robust", "resnet50"]
REVIEWER_LIST    = ["resnet50_robust", "resnet50"]
UNIT_IDS         = [0, 2, 9, 15, 19]

os.makedirs(FIGDIR, exist_ok=True)


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------
def load_neural_session(session_id: str) -> tuple[pd.DataFrame, np.ndarray, list[int]]:
    """Load accentuation session: returns (df_allstim_w_resp, respmat, unit_list)."""
    data_path = join(EPHYS_DIR, "vvs-accentuate_controlsessions_5monkeys_250504-250512.h5")
    data = load_from_hdf5(data_path)

    respmat    = data[session_id]["repavg"]["response_peak"]          # (n_stims, n_units)
    stimnames  = data[session_id]["repavg"]["stimulus_name"]
    stimnames_str = [s.decode("utf-8") if isinstance(s, bytes) else s for s in stimnames]

    print(f"Loaded {session_id}: {respmat.shape[0]} stims, {respmat.shape[1]} units")

    df = parse_accentuated_filenames_to_df(stimnames_str, include_parse_fail=True)

    # Attach neural responses for all driven units
    unit_list = sorted([int(u) for u in df.unit_id.dropna().unique()])
    for unit in unit_list:
        df[f"neural_resp_unit_{unit}"] = respmat[:, unit]

    return df, respmat, unit_list


def load_model_predictions(encoding_session_id: str) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Load model predicted responses for NSD and accentuated stimuli."""
    posthoc_dir = join(ENCODING_DIR, encoding_session_id, "posthoc_model_predict")

    df_encoding = pd.read_pickle(
        join(posthoc_dir, f"encoding_stim_info_w_pred_resp_{encoding_session_id}.pkl"))
    df_accentuated = pd.read_pickle(
        join(posthoc_dir, f"accentuated_stim_info_w_pred_resp_{encoding_session_id}.pkl"))
    df_accentuated["basename"] = df_accentuated["filepath"].apply(os.path.basename)

    return df_encoding, df_accentuated


def build_nsd_df(df_allstim: pd.DataFrame, df_encoding: pd.DataFrame) -> pd.DataFrame:
    """Merge NSD natural images with model predictions."""
    df_nat = df_allstim.query("model_name.isna()").copy()
    df_nat = df_nat.drop(columns=["model_name", "unit_id", "img_id", "level", "score"],
                         errors="ignore")

    # Fix is_test column if stored as mixed types
    df_enc = df_encoding.copy()
    df_enc["is_test"] = df_enc["is_test"].map(
        {1: True, 0: False, "1": True, "0": False, "True": True, "False": False,
         True: True, False: False}).astype(bool)

    df_merged = pd.merge(df_nat, df_enc,
                         how="inner",
                         left_on="filepath",
                         right_on="stimulus_name")
    print(f"NSD merged: {len(df_merged)} rows")
    return df_merged


def build_accentuated_df(df_allstim: pd.DataFrame,
                         df_acc_pred: pd.DataFrame) -> pd.DataFrame:
    """Merge accentuated stimuli model predictions with neural responses."""
    df_merged = df_acc_pred.merge(
        df_allstim,
        left_on=["basename", "img_id", "unit_id", "model_name"],
        right_on=["filepath", "img_id", "unit_id", "model_name"],
        how="inner",
        suffixes=("", "_dfallstim"),
    )
    # Sanity check: score and level must agree between tables
    for col in ["score", "level"]:
        col2 = f"{col}_dfallstim"
        if col2 in df_merged.columns:
            assert np.allclose(
                df_merged[col].astype(float),
                df_merged[col2].astype(float),
                atol=1e-5, equal_nan=True,
            ), f"Column '{col}' mismatch between tables"
    print(f"Accentuated merged: {len(df_merged)} rows, units: {sorted(df_merged.unit_id.unique())}")
    return df_merged


# ---------------------------------------------------------------------------
# Plot helpers
# ---------------------------------------------------------------------------
def _scatter_with_stats(ax, df, xvar, yvar, hue=None, palette="tab10"):
    """Scatter plot with y=x line and r/R²/N annotation."""
    scatter_kwargs = dict(data=df, x=xvar, y=yvar, alpha=0.6,
                          legend=(hue is not None), ax=ax)
    if hue is not None:
        scatter_kwargs.update(hue=hue, palette=palette)
    sns.scatterplot(**scatter_kwargs)

    x, y = df[xvar], df[yvar]
    mask = x.notna() & y.notna()
    if mask.sum() > 1:
        corr, _ = pearsonr(x[mask], y[mask])
        r2      = r2_score(y[mask], x[mask])
    else:
        corr = r2 = float("nan")

    # Equal axes + y=x line
    lims = [min(ax.get_xlim()[0], ax.get_ylim()[0]),
            max(ax.get_xlim()[1], ax.get_ylim()[1])]
    ax.set_xlim(lims); ax.set_ylim(lims)
    ax.axline((0, 0), slope=1, linestyle="--", color="gray", lw=1)

    ax.text(0.97, 0.05,
            f"r = {corr:.2f}\nR² = {r2:.2f}\nN = {mask.sum()}",
            transform=ax.transAxes, ha="right", va="bottom",
            fontsize=10, bbox=dict(boxstyle="round", fc="white", alpha=0.7))

    ax.set_xlabel("Predicted response")
    ax.set_ylabel("Neural response")


# ---------------------------------------------------------------------------
# Figure 1: NSD validation — stacked reviewer panels
# ---------------------------------------------------------------------------
def fig_nsd_stacked(df_merged: pd.DataFrame, unit_id: int,
                    reviewer_list: list[str]) -> plt.Figure:
    """Neural vs predicted on NSD images, one panel per reviewer model."""
    yvar = f"neural_resp_unit_{unit_id}"
    fig, axes = plt.subplots(len(reviewer_list), 1,
                             figsize=(4, 4 * len(reviewer_list)),
                             sharex=True, sharey=True)
    if len(reviewer_list) == 1:
        axes = [axes]

    for ax, reviewer in zip(axes, reviewer_list):
        xvar = f"pred_resp_{reviewer}_unit_{unit_id}"
        _scatter_with_stats(ax, df_merged, xvar, yvar, hue=None)
        ax.set_title(f"Reviewer: {reviewer}", fontsize=10)

    fig.suptitle(f"NSD images — {ACC_SESSION_ID}\nUnit {unit_id}", fontsize=12)
    fig.tight_layout()
    return fig


# ---------------------------------------------------------------------------
# Figure 2: Accentuated 2×2 (accentuator × reviewer)
# ---------------------------------------------------------------------------
def _get_palette(n_colors: int, palette: str = "tab10") -> list:
    return sns.color_palette(palette, n_colors)


def fig_acc_2x2(accentuated_merged_df: pd.DataFrame, unit_id: int,
                accentuator_list: list[str],
                reviewer_list: list[str]) -> plt.Figure:
    """
    2x2 grid: rows = accentuator model, cols = reviewer model.
    y = neural response, x = reviewer predicted response.
    Points colored by img_id. Dots connected by thin colored lines per img_id.
    Stats annotation placed outside each panel on the right.
    """
    yvar   = f"neural_resp_unit_{unit_id}"
    n_rows = len(accentuator_list)
    n_cols = len(reviewer_list)

    fig, axes = plt.subplots(n_rows, n_cols,
                             figsize=(5 * n_cols, 4.5 * n_rows),
                             constrained_layout=True,
                             sharex=True, sharey=True)
    if n_rows == 1 and n_cols == 1:
        axes = np.array([[axes]])
    elif n_rows == 1:
        axes = axes[np.newaxis, :]
    elif n_cols == 1:
        axes = axes[:, np.newaxis]

    for i, accentuator in enumerate(accentuator_list):
        df_sub  = accentuated_merged_df.query(
            "model_name == @accentuator and unit_id == @unit_id"
        ).copy()
        img_ids = sorted(df_sub["img_id"].unique())
        palette = _get_palette(len(img_ids))
        color_map = {iid: palette[k] for k, iid in enumerate(img_ids)}

        for j, reviewer in enumerate(reviewer_list):
            ax   = axes[i, j]
            xvar = f"pred_resp_{reviewer}_unit_{unit_id}"

            # --- compute limits from data BEFORE plotting so nothing is clipped ---
            x_vals = df_sub[xvar].dropna()
            y_vals = df_sub[yvar].dropna()
            pad  = 0.05 * (max(x_vals.max(), y_vals.max()) -
                           min(x_vals.min(), y_vals.min()))
            vmin = min(x_vals.min(), y_vals.min()) - pad
            vmax = max(x_vals.max(), y_vals.max()) + pad
            ax.set_xlim(vmin, vmax)
            ax.set_ylim(vmin, vmax)

            # --- connected lines per img_id (behind dots) ---
            for iid in img_ids:
                grp = df_sub[df_sub["img_id"] == iid].sort_values("level")
                ax.plot(grp[xvar], grp[yvar],
                        color=color_map[iid], alpha=0.5, lw=0.8, zorder=1)

            # --- scatter (larger markers) ---
            for iid in img_ids:
                grp = df_sub[df_sub["img_id"] == iid]
                ax.scatter(grp[xvar], grp[yvar],
                           color=color_map[iid], s=50, alpha=0.7,
                           zorder=2, label=str(iid))

            # --- y=x reference line ---
            ax.axline((0, 0), slope=1, linestyle="--", color="gray", lw=1)

            # --- stats inside panel, top left ---
            mask = df_sub[xvar].notna() & df_sub[yvar].notna()
            if mask.sum() > 1:
                corr, _ = pearsonr(df_sub.loc[mask, xvar], df_sub.loc[mask, yvar])
                r2      = r2_score(df_sub.loc[mask, yvar], df_sub.loc[mask, xvar])
            else:
                corr = r2 = float("nan")
            ax.text(0.05, 0.95,
                    f"r = {corr:.2f}\nR² = {r2:.2f}\nN = {mask.sum()}",
                    transform=ax.transAxes, ha="left", va="top",
                    fontsize=9, bbox=dict(boxstyle="round", fc="white",
                                         ec="lightgray", alpha=0.85))

            # --- legend only on the final panel (bottom-right) ---
            is_last = (i == len(accentuator_list) - 1) and (j == len(reviewer_list) - 1)
            if is_last:
                ax.legend(title="img_id", bbox_to_anchor=(1.01, 1),
                          loc="upper left", fontsize=7, title_fontsize=8,
                          framealpha=0.8)
            else:
                leg = ax.get_legend()
                if leg: leg.remove()

            ax.set_xlabel("Predicted response")
            ax.set_ylabel("Neural response")
            ax.set_title(f"Accentuator: {accentuator}\nReviewer: {reviewer}", fontsize=9)
            ax.tick_params(left=True, bottom=True, labelleft=True, labelbottom=True)

    fig.suptitle(
        f"Accentuated images — {ACC_SESSION_ID}\nUnit {unit_id}",
        fontsize=13)
    return fig


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main():
    # Load data
    df_allstim, respmat, unit_list = load_neural_session(ACC_SESSION_ID)
    df_encoding, df_acc_pred       = load_model_predictions(ENCODING_SESSION_ID)

    df_nsd_merged = build_nsd_df(df_allstim, df_encoding)
    df_acc_merged = build_accentuated_df(df_allstim, df_acc_pred)

    for unit_id in UNIT_IDS:
        print(f"\n--- Unit {unit_id} ---")

        # Fig 1: NSD validation
        fig = fig_nsd_stacked(df_nsd_merged, unit_id, REVIEWER_LIST)
        saveallforms(FIGDIR, f"acc_peer_review_{ACC_SESSION_ID}_U{unit_id}_NSD_stacked", figh=fig)
        plt.close(fig)

        # Fig 2: Accentuated 2×2
        fig = fig_acc_2x2(df_acc_merged, unit_id, ACCENTUATOR_LIST, REVIEWER_LIST)
        saveallforms(FIGDIR, f"acc_peer_review_{ACC_SESSION_ID}_U{unit_id}_acc_2x2", figh=fig)
        plt.close(fig)

        print(f"  Saved figures for unit {unit_id} → {FIGDIR}")

    print("\nDone.")


if __name__ == "__main__":
    main()
